services:
  db:
    # Defines the 'db' service for MySQL database
    image: mysql:8.0 # Uses the MySQL 8.0 Docker image
    environment:
      # Sets environment variables for the database configuration
      - MYSQL_DATABASE=appdb # Specifies the name of the database
      - MYSQL_PASSWORD=pass123 # Sets the password for the MySQL user
      - MYSQL_ROOT_PASSWORD=pass123 # Sets the root password for MySQL
    ports:
      - 8000:3306 # Maps the container's port 3306 to the host's port 3307
  app:
      # Defines the 'app' service for the Next.js app
      build:
        # Builds the Next.js app using the provided Dockerfile
        context: ./eventstar
      environment:
        NODE_ENV: production
        HOSTNAME: "0.0.0.0"
        PORT: 3000
        DATABASE_URL: mysql://root:pass123@db:3306/appdb
      ports:
        - 3000:3000 # Maps the container's port 3000 to the host's port 3000
      depends_on:
        - db # Specifies that the 'app' service depends on the 'db' service