services:
  es_db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=costi_online
      - MYSQL_PASSWORD=0_0
      - MYSQL_ROOT_PASSWORD=0_0
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_GITHUB_ID=admin
      - AUTH_GITHUB_SECRET=admin
      - AUTH_GOOGLE_ID=admin
      - AUTH_GOOGLE_SECRET=admin
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_SECRET=admin
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p0_0" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 3308:3306
    networks:
      - shared_network
  app:
    restart: unless-stopped
    build:
      context: ./
      target: runner
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
      PORT: 3000
      DATABASE_URL: mysql://root:0_0@es_db:3306/costi_online
    ports:
      - 3000:3000
    depends_on:
      es_db:
        condition: service_healthy
    networks:
      - shared_network

networks:
  shared_network:
    name: costi_online_network
    external: true